default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

<%= Rails.env %>:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:postgresql][:DB_NAME] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:postgresql][:DB_HOST] %>
  pool: 5
  username: <%= Rails.application.credentials[Rails.env.to_sym][:postgresql][:DB_USER] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:postgresql][:DB_PASSWORD] %>
